lista = ['Não critique, não condene, não se queixe.',
         'Aprecie honesta e sinceramente.',
         'Desperte um forte desejo nos demais.',
         'Torne-se verdadeiramente interessado na outra pessoa.',
         'Sorria.',
         'Lembre-se de que o nome de uma pessoa é para ela o som mais doce em qualquer idioma.',
         'Seja um bom ouvinte. Incentive os outros a falarem sobre si mesmos.',
         'Fale de coisas que interessem à outra pessoa.',
         'Faça a outra pessoa sentir-se importante e faça isso com sinceridade.',
         'A única maneira de ganhar uma discussão é evitando-a.',
         'Respeite a opinião dos outros. Nunca diga a uma pessoa que ela está errada.',
         'Se você estiver errado, reconheça o seu erro rápida e energicamente.',
         'Comece de uma maneira amigável.',
         'Leve a outra pessoa a dizer “sim” imediatamente.',
         'Deixe a outra pessoa falar a maior parte da conversa.',
         'Deixe que a outra pessoa sinta que a ideia é dela.',
         'Procure honestamente ver as questões do ponto de vista da outra pessoa.',
         'Seja receptivo às ideias e anseios da outra pessoa.',
         'Apele para os “motivos mais nobres.',
         'Dramatize as suas ideias.',
         'Lance um desafio.',
         'Comece com um elogio e uma apreciação sincera.',
         'Chame a atenção para os erros das pessoas de forma indireta.',
         'Fale sobre os próprios erros antes de criticar os da outra pessoa.',
         'Faça perguntas em vez de dar ordens diretas.',
         'Permita que a outra pessoa corrija os próprios erros.',
         'Elogie o menor progresso e elogie cada progresso. Seja “sincero na sua apreciação e generoso no seu elogio”.',
         'Proporcione à outra pessoa uma boa reputação para ela zelar.',
         'Empregue o incentivo. Faça com que o erro pareça fácil de ser corrigido.',
         'Faça com que a outra pessoa se sinta feliz realizando o que você sugere.'
         ]
